#include <stdio.h>
#include <stdlib.h>

int main()
{
    system("COLOR 13");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    getch();
    system("cls");
    printf("Made By Maysun Campos\n");
    printf("-------------------------------\n");
    printf("Press Anykey To Switch Colors\n");
    system("COLOR 02");
    getch();
    return 0;
}
